name: Deploy automático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 100.105.76.50 >> ~/.ssh/known_hosts

      - name: Rodar deploy no servidor
        run: |
          ssh -i ~/.ssh/id_ed25519 fsl@100.105.76.50 "
            cd /var/www/html &&
            git pull origin main

          
  run: |
    ssh -i ~/.ssh/id_ed25519 fsl@100.105.76.50 "
      echo 'Entrando no diretório...' &&
      cd /var/www/html &&
      echo 'Fazendo git pull...' &&
      git pull origin main &&
      echo 'Deploy concluído!'
    "
